### ISSUE TITLE
 Account responsible for LFS bandwidth should purchase more data packs to restore access.

### ISSUE THREAD

**Issue by jardnzm** [staplesinLA/first_com#11]
Hi,
I am unable to clone or pull from Github because of a git-lfs quota.
`(base) ➜  ami git lfs clone https://github.com/staplesinLA/denoising_DIHARD18.git
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
Cloning into 'denoising_DIHARD18'...
remote: Enumerating objects: 234, done.
remote: Total 234 (delta 0), reused 0 (delta 0), pack-reused 234
Receiving objects: 100% (234/234), 123.07 KiB | 2.09 MiB/s, done.
Resolving deltas: 100% (132/132), done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                               
error: failed to fetch some objects from 'https://github.com/staplesinLA/denoising_DIHARD18.git/info/lfs'`

I yesterday cloned several times since I used a docker and it automatically re-cloned everytime I ran it. For this problem I feel responsible and would be happy to pay for one git-lfs pack for this month since I also need to re-download it (but only once this time😂). https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/upgrading-git-large-file-storage. 
You can shoot me an email lloqiolloqio@gmail.com

**Comment by staplesinLA** [comment]
Already updated a download link.
